version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: celestiquerootsecret
      MYSQL_DATABASE: celestique_db
      MYSQL_USER: team4
      MYSQL_PASSWORD: team4secret
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel
    depends_on:
      - mysql
      - redis
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./backend/storage:/var/www/storage
      - ./backend/bootstrap/cache:/var/www/bootstrap/cache
    environment:
      DB_HOST: mysql
      DB_DATABASE: celestique_db
      DB_USERNAME: team4
      DB_PASSWORD: team4secret
      REDIS_HOST: redis
      REDIS_PORT: 6379
    # command: php artisan queue:work
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
