FROM php:8.3.14-apache
WORKDIR /var/www

#update install dependencies, install laravel, install dependencies
RUN apt-get update && apt-get install -y \
    git curl zip unzip libpng-dev libonig-dev libxml2-dev libzip-dev \
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd zip

# for routing and to enable using 'localhost' in the browser
RUN a2enmod rewrite \
    && echo "ServerName localhost" >> /etc/apache2/apache2.conf

#change Apache’s default web root to /public.
#sed is linux command for 'stream editor'
#s(search)| search term | replace term |gloabl (all occurrences) 
RUN sed -i 's|DocumentRoot /var/www/html|DocumentRoot /var/www/public|g' /etc/apache2/sites-available/000-default.conf

#copy composer from composer v2
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

#copy backend files to WORKDIR
COPY . .

#define apache user and set read/write permissions
RUN chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache \
    && chmod -R 755 /var/www/storage /var/www/bootstrap/cache

EXPOSE 80

CMD ["apache2-foreground"]