name: Laravel Feature Tests CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: testing_db
      DB_USERNAME: root
      DB_PASSWORD: root

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, xml, mysql, curl, zip

      - name: Install Composer dependencies
        working-directory: ./server
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Copy .env and generate key
        working-directory: ./server
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run migrations
        working-directory: ./server
        run: php artisan migrate --force

      - name: Run Laravel feature tests
        working-directory: ./server
        run: php artisan test --testsuite=Feature
